[package]
edition = "2021"
name = "unnamedOS"
version = "0.0.3"

[dependencies]
bootloader = "0.9"
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0"
